<a href="https://colab.research.google.com/github/abhirules27/Machine_Learning/blob/From_Google_Colab/Pandas_read_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Day 14

# Business Problem to ML
# Example of NetFlix
# Reducting Churn Rate

## Step 3: Getting Data:
# 1. Watch Time Analysis
# 2. Search but did not find
# 3. Content left in middle
# 4. Clicked on recom (Order of Recoms)

## Step 4: Data Engineer will give:
# OLTP -> DW

## Step 5: Metrics to Measure

## Step 6: Online vs Batch Learning

## Step 7: Check Assumptions

# ___________________________________________

**Day 15: Data Gathering**

1.   Data Gathering from Files:
*   CSV
*   JSON/SQL

2.   Fetch API

3.   Web Scrapping

In [30]:
# Todays Focus -> CSV
# Source - pandas.pydata.org/docs/reference/api/pandas.read_csv/html

In [4]:
import pandas as pd

In [8]:
# Loading from File present in the Machine

df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [10]:
# Loading CSV from URL

import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [12]:
# Separater Parameter - Tab instead of Comma

pd.read_csv('/content/sample_data/california_housing_test.csv', sep = '\t')   # \t means Tab

     longitude,"latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","median_house_value"
0     -122.050000,37.370000,27.000000,3885.000000,66...
1     -118.300000,34.260000,43.000000,1510.000000,31...
2     -117.810000,33.780000,27.000000,3589.000000,50...
3     -118.360000,33.820000,28.000000,67.000000,15.0...
4     -119.670000,36.330000,19.000000,1241.000000,24...
...                                                 ...
2995  -119.860000,34.420000,23.000000,1450.000000,64...
2996  -118.140000,34.060000,27.000000,5257.000000,10...
2997  -119.700000,36.300000,10.000000,956.000000,201...
2998  -117.120000,34.100000,40.000000,96.000000,14.0...
2999  -119.630000,34.420000,42.000000,1765.000000,26...

[3000 rows x 1 columns]

In [13]:
# If Coln header is not coming and first row itself becomes Header
# Pass own list as names


# pd.read_csv('/content/sample_data/california_housing_test.csv', sep = '\t', names = ['Coln1','Coln2'...])   # \t means Tab

In [14]:
# Index_Col Parameter
# Used when we have multiple index coln
# If you are sure about any existing Coln, you can make it as Index


# pd.read_csv('/content/sample_data/california_housing_test.csv', sep = '\t', index_col='col_xyz')   # \t means Tab

In [15]:
# Header Parameter
# When you want to use first row as header

# pd.read_csv('test.csv', header = 1)

In [16]:
# Use_cols Parameters
# Not necessarily we require all colns. We can choose which coln only we want

# pd.read_csv('test.csv', usecols=['col1','col3','col6'])

In [17]:
# Squeeze Parameter
# Panda dataframe becomes series

# pd.read_csv('test.csv', usecols=['gender'], squeeze = True)

In [19]:
# Skiprows/nrows Parameter
# That No row cn be skipped from coming in DataFrame

pd.read_csv('/content/sample_data/california_housing_test.csv', skiprows = [0,5,10])

,-122.050000,37.370000,27.000000,3885.000000,661.000000,1537.000000,606.000000,6.608500,344700.000000
0,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
1,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
2,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
3,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
4,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
...,...,...,...,...,...,...,...,...,...
2992,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2993,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2994,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2995,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2996,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [20]:
# nrows -> only this row value will come
pd.read_csv('/content/sample_data/california_housing_test.csv', nrows=10) # shows only 10 rows

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0

In [21]:
# Encoding Parameter
# Used when DataFrame has not Encoding as UTF-8
# Option 1- Go to sublime text type editor and change the encoding value
# Option 2- If you know Encoding type, then you can change it

# pd.read_csv('Test.csv', encoding = 'latin-1')

In [25]:
# Skip bad lines
# pd.read_csv('/content/sample_data/california_housing_test.csv', error = False)

In [27]:
# dtypes Parameter (Data Types)

pd.read_csv('/content/sample_data/california_housing_test.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

In [28]:

pd.read_csv('/content/sample_data/california_housing_test.csv', dtype = {'population':int}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   int64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 211.1 KB

In [29]:
# Handling Dates
# By default all Date becomes string
# Date functionalities can not be fetched

# pd.read_csv('Test.csv', parse_dates = ['put_name_of_date_col'])

In [33]:
# Convertors
# When you want to apply some transformations even before loading it
# Royal Challengers Bangalore -> RCB

def rename(name):
  if name == "Royal Challengers Bangalore":
    return "RCB"
  else:
    return name

In [34]:
rename ("Royal Challengers Bangalore")

'RCB'

In [38]:
# pd.read_csv('Test.csv', converters = {'team1' : rename})

In [36]:
# na_values Parameter
# NaN Values
# Problem comes when Missing Values are / or - or etc

# pd.read_csv('Test.csv', na_values = ['/', '-', 'something_else']) # All these values will be considered as NaN

In [40]:
# Loading a huge DataSet in Chunks
# When you don't have that big RAM to handle big DataSets

dfs = pd.read_csv('/content/sample_data/california_housing_test.csv', chunksize=500)
for chunks in dfs:
  print(chunks.shape)

(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)
(500, 9)